language: cpp
before_install: 
 - sudo apt-get update
 - sudo apt-get install linux-image-generic-lts-raring linux-headers-generic-lts-raring
 - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
 - sudo sh -c "echo deb http://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
 - sudo apt-get update
 - echo exit 101 | sudo tee /usr/sbin/policy-rc.d
 - sudo chmod +x /usr/sbin/policy-rc.d
install: 
 - sudo apt-get install lxc-docker
script: 
 - ./builddocker.sh
notifications:
   hipchat: dc42889c409c6cd69161db13033628@papino

